### ISSUE TITLE
module_util.extract_decomposable_modules can't extract the yaml whose net is replaced by shufflenetV2

### ISSUE THREAD

**Issue by WangzcBruce** [yoshitomo-matsubara/myutils#43]
it will return none. But mobilenet series won't get none error
![image](https://user-images.githubusercontent.com/45158420/195796065-0be8a36e-29cf-4e24-9d48-21c74581bb43.png)
![image](https://user-images.githubusercontent.com/45158420/195796201-8cc7d545-917c-4672-a942-a3dfb4e469c3.png)

**Comment by WangzcBruce** [comment]
squeezenet  also happened that

**Comment by yoshitomo-matsubara** [comment]
Hi @WangzcBruce 

> it will return none. But mobilenet series won't get none error

I need more clarifications as you're showing only ShuffleNetV2. Did you confirm that MobileNet series work without errors? Is that what you mean by "get none error"?

A potential issue with ShuffleNetV2 is due to [non-module-based operation here](https://github.com/pytorch/vision/blob/main/torchvision/models/shufflenetv2.py#L161), which cannot be extracted by `extract_decomposable_modules` as it will fail to verify the sequence of decomposed modules produces the same output as the original model.

**Comment by WangzcBruce** [comment]
Thanks!I debugged yesterday and found that the model.extract_decomposable_modules can't distinguish the branch1 and branch2 in the shufflenet, which are parallelly performed during the net .However, the module performed two modules serially.

**Comment by yoshitomo-matsubara** [comment]
`branch1` and `branch2` are modules at the one-step lower level, and such modules won't be decomposed by `extract_decomposable_modules` 

My comment above explains why you got `None`. If you define AvgPool2d like `self.avgpool = AvgPool2d(**some_params)` and replace [non-module-based operation here](https://github.com/pytorch/vision/blob/main/torchvision/models/shufflenetv2.py#L161) with `self.avgpool`, then you could get a list of at least modules directly registered in ShuffleNetV2 class
